name: BE PR CI

on:
  push:
    branches:
      - main
      - develop-be
  pull_request:
    branches:
      - main
      - develop-be

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - uses: reitzig/actions-asciidoctor@v2.0.0
        with:
          version: 2.0.10

      - run: asciidoctor --version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --warning-mode all --exclude-task test

      - name: Test
        run: ./gradlew test
